# DATA V2 Projet 4 OpenClassRoom 
## Analyse des fichiers de bases
### Importation des bibliothèques et import des fichiers

In [1]:
# import de pandas
import pandas as pd

In [2]:
#import des fichiers csv dans le repertoire du notebook
population = pd.read_csv('donnee/population.csv')
sous_nutrition = pd.read_csv('donnee/sous_nutrition.csv')
aide_alimentaire = pd.read_csv('donnee/aide_alimentaire.csv')
dispo_alimentaire = pd.read_csv('donnee/dispo_alimentaire.csv')

### Vérification du fichier population.csv

In [3]:
population.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1416 entries, 0 to 1415
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Zone    1416 non-null   object
 1   Année   1416 non-null   int64
 2   Valeur  1416 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 33.3+ KB

In [4]:
#Verification voir si il y a des Doublons 
population[population.duplicated()]

Empty DataFrame
Columns: [Zone, Année, Valeur]
Index: []

### Vérification du fichier sous_nutrition.csv

In [5]:
sous_nutrition.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Zone    1218 non-null   object
 1   Année   1218 non-null   object
 2   Valeur  624 non-null    object
dtypes: object(3)
memory usage: 28.7+ KB

In [6]:
#nombre de valeur null dans sous nutrition
sous_nutrition.isna().sum()

Zone        0
Année       0
Valeur    594
dtype: int64

In [7]:
sous_nutrition[sous_nutrition.duplicated()]

Empty DataFrame
Columns: [Zone, Année, Valeur]
Index: []

In [8]:
#création d'un sous data avec que les Nan, pour analyser des Nan 
sous_nutritionNan = sous_nutrition[sous_nutrition['Valeur'].isna()]
print(sous_nutritionNan)

           Zone      Année Valeur
24    Allemagne  2012-2014    NaN
25    Allemagne  2013-2015    NaN
26    Allemagne  2014-2016    NaN
27    Allemagne  2015-2017    NaN
28    Allemagne  2016-2018    NaN
...         ...        ...    ...
1213   Zimbabwe  2013-2015    NaN
1214   Zimbabwe  2014-2016    NaN
1215   Zimbabwe  2015-2017    NaN
1216   Zimbabwe  2016-2018    NaN
1217   Zimbabwe  2017-2019    NaN

[594 rows x 3 columns]

In [9]:
#affichage des pays avec des Nan
print(sous_nutritionNan['Zone'].unique())

['Allemagne' 'Andorre' 'Antigua-et-Barbuda' 'Argentine' 'Australie'
 'Autriche' 'Azerbaïdjan' 'Bahamas' 'Bahreïn' 'Bélarus' 'Belgique'
 'Bermudes' 'Bhoutan' 'Bosnie-Herzégovine' 'Brésil' 'Brunéi Darussalam'
 'Burundi' 'Canada' 'Chine - RAS de Hong-Kong' 'Chine, continentale'
 'Comores' 'Croatie' 'Cuba' 'Danemark' 'Djibouti' 'Érythrée' 'Espagne'
 'Estonie' "États-Unis d'Amérique" 'Fédération de Russie' 'Finlande'
 'France' 'Grèce' 'Grenade' 'Groenland' 'Guinée' 'Guinée équatoriale'
 'Guinée-Bissau' 'Hongrie' 'Îles Cook' 'Îles Marshall' 'Irlande' 'Islande'
 'Israël' 'Italie' 'Japon' 'Kazakhstan' 'Koweït' 'Lettonie' 'Libye'
 'Lituanie' 'Luxembourg' 'Maldives' 'Malte'
 'Micronésie (États fédérés de)' 'Monténégro' 'Nauru' 'Niger' 'Nioué'
 'Norvège' 'Nouvelle-Zélande' 'Ouganda' 'Palaos' 'Palestine'
 'Papouasie-Nouvelle-Guinée' 'Pays-Bas' 'Pologne' 'Porto Rico' 'Portugal'
 'Qatar' 'République arabe syrienne' 'République centrafricaine'
 'République de Corée' 'République de Moldova'
 'République démocratique du Congo'
 'République démocratique populaire lao' 'Roumanie'
 "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord" 'Sainte-Lucie'
 'Saint-Kitts-et-Nevis' 'Samoa' 'Samoa américaines' 'Seychelles'
 'Singapour' 'Slovénie' 'Somalie' 'Soudan du Sud' 'Suède' 'Suisse'
 'Tadjikistan' 'Tchéquie' 'Tokélaou' 'Tonga' 'Tunisie' 'Turquie' 'Tuvalu'
 'Ukraine' 'Uruguay' 'Yémen' 'Zambie' 'Zimbabwe']

In [10]:
# cast non possible car certaines valeurs sont mal formatées (string), je les remplace par 0
print (sous_nutrition.loc[(sous_nutrition['Valeur'] == '<0.1')])

         Zone      Année Valeur
60    Arménie  2012-2014   <0.1
61    Arménie  2013-2015   <0.1
62    Arménie  2014-2016   <0.1
63    Arménie  2015-2017   <0.1
64    Arménie  2016-2018   <0.1
...       ...        ...    ...
1183  Vanuatu  2013-2015   <0.1
1184  Vanuatu  2014-2016   <0.1
1185  Vanuatu  2015-2017   <0.1
1186  Vanuatu  2016-2018   <0.1
1187  Vanuatu  2017-2019   <0.1

[120 rows x 3 columns]

In [11]:
#Année: prévoir de changer les 201X-201Y en int(210x+1)
sous_nutrition.head()

          Zone      Année Valeur
0  Afghanistan  2012-2014    8.6
1  Afghanistan  2013-2015    8.8
2  Afghanistan  2014-2016    8.9
3  Afghanistan  2015-2017    9.7
4  Afghanistan  2016-2018   10.5

### Vérification aide_alimentaire.csv

In [12]:
aide_alimentaire.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1475 entries, 0 to 1474
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Pays bénéficiaire  1475 non-null   object
 1   Année              1475 non-null   int64
 2   Produit            1475 non-null   object
 3   Valeur             1475 non-null   int64
dtypes: int64(2), object(2)
memory usage: 46.2+ KB

In [13]:
#verification des doublons
aide_alimentaire[aide_alimentaire.duplicated()]

Empty DataFrame
Columns: [Pays bénéficiaire, Année, Produit, Valeur]
Index: []

### Vérification du fichier dispo_alimentaire.csv

In [14]:
dispo_alimentaire.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15605 entries, 0 to 15604
Data columns (total 18 columns):
 #   Column                                                         Non-Null Count  Dtype
---  ------                                                         --------------  -----
 0   Zone                                                           15605 non-null  object
 1   Produit                                                        15605 non-null  object
 2   Origine                                                        15605 non-null  object
 3   Aliments pour animaux                                          2720 non-null   float64
 4   Autres Utilisations                                            5496 non-null   float64
 5   Disponibilité alimentaire (Kcal/personne/jour)                 14241 non-null  float64
 6   Disponibilité alimentaire en quantité (kg/personne/an)         14015 non-null  float64
 7   Disponibilité de matière grasse en quantité (g/personne/jour)  11794 non-null  float64
 8   Disponibilité de protéines en quantité (g/personne/jour)       11561 non-null  float64
 9   Disponibilité intérieure                                       15382 non-null  float64
 10  Exportations - Quantité                                        12226 non-null  float64
 11  Importations - Quantité                                        14852 non-null  float64
 12  Nourriture                                                     14015 non-null  float64
 13  Pertes                                                         4278 non-null   float64
 14  Production                                                     9180 non-null   float64
 15  Semences                                                       2091 non-null   float64
 16  Traitement                                                     2292 non-null   float64
 17  Variation de stock                                             6776 non-null   float64
dtypes: float64(15), object(3)
memory usage: 2.1+ MB

In [15]:
#verification des doublons
dispo_alimentaire[dispo_alimentaire.duplicated()]

Empty DataFrame
Columns: [Zone, Produit, Origine, Aliments pour animaux, Autres Utilisations, Disponibilité alimentaire (Kcal/personne/jour), Disponibilité alimentaire en quantité (kg/personne/an), Disponibilité de matière grasse en quantité (g/personne/jour), Disponibilité de protéines en quantité (g/personne/jour), Disponibilité intérieure, Exportations - Quantité, Importations - Quantité, Nourriture, Pertes, Production, Semences, Traitement, Variation de stock]
Index: []

### Vérification des équations de Julien

In [16]:
dispo_alimentaire.loc[107:110]

,Zone,Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock
107,Afrique du Sud,Lait - Excl Beurre,animale,123.0,NaN,85.0,55.75,5.26,4.55,3093.0,697.0,292.0,2942.0,32.0,3260.0,NaN,0.0,238.0
108,Afrique du Sud,"Légumes, Autres",vegetale,51.0,NaN,23.0,25.08,0.22,0.93,1511.0,194.0,78.0,1323.0,137.0,1621.0,NaN,0.0,5.0
109,Afrique du Sud,Légumineuses Autres,vegetale,18.0,NaN,2.0,0.23,0.01,0.14,30.0,2.0,8.0,12.0,0.0,24.0,1.0,NaN,0.0
110,Afrique du Sud,Manioc,vegetale,NaN,57.0,0.0,0.00,0.00,0.00,57.0,2.0,58.0,0.0,NaN,NaN,NaN,NaN,1.0

In [17]:
dispo_alimentaire = dispo_alimentaire.fillna(0) #mets des 0 à la place des Nan

dispo_alimentaire['test dispo1'] = (dispo_alimentaire['Production']
                                    + dispo_alimentaire['Importations - Quantité']
                                    + dispo_alimentaire['Variation de stock']
                                    - dispo_alimentaire['Exportations - Quantité']
                                    - dispo_alimentaire['Disponibilité intérieure']
                                   )

dispo_alimentaire[dispo_alimentaire['test dispo1']!=0]

,Zone,Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,test dispo1
30,Afghanistan,"Légumes, Autres",vegetale,0.0,0.0,17.0,28.97,0.13,0.85,1007.0,34.0,124.0,885.0,122.0,916.0,0.0,0.0,0.0,-1.0
46,Afghanistan,Raisin,vegetale,0.0,0.0,29.0,15.80,0.12,0.27,513.0,97.0,0.0,483.0,31.0,611.0,0.0,0.0,0.0,1.0
48,Afghanistan,Sucre Eq Brut,vegetale,0.0,0.0,84.0,8.35,0.00,0.00,255.0,0.0,271.0,255.0,0.0,2.0,0.0,0.0,-19.0,-1.0
56,Afghanistan,Viande de Volailles,animale,0.0,0.0,9.0,2.45,0.53,0.87,75.0,0.0,48.0,75.0,0.0,26.0,0.0,0.0,0.0,-1.0
63,Afrique du Sud,Aliments pour enfants,vegetale,0.0,0.0,0.0,0.00,0.00,0.00,0.0,5.0,2.0,0.0,0.0,0.0,0.0,0.0,2.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15565,Îles Salomon,"Légumes, Autres",vegetale,0.0,0.0,8.0,12.96,0.06,0.42,8.0,0.0,0.0,7.0,0.0,7.0,0.0,0.0,0.0,-1.0
15584,Îles Salomon,"Poissons Marins, Autres",animale,0.0,0.0,36.0,19.01,1.33,5.57,11.0,2.0,2.0,11.0,0.0,10.0,0.0,0.0,0.0,-1.0
15585,Îles Salomon,Poissons Pelagiques,animale,0.0,0.0,32.0,13.60,1.34,4.69,8.0,18.0,0.0,8.0,0.0,25.0,0.0,0.0,0.0,-1.0
15591,Îles Salomon,Riz (Eq Blanchi),vegetale,0.0,12.0,623.0,63.76,1.36,10.90,49.0,0.0,47.0,36.0,1.0,3.0,0.0,0.0,0.0,1.0
15600,Îles Salomon,Viande de Suides,animale,0.0,0.0,45.0,4.70,4.28,1.41,3.0,0.0,0.0,3.0,0.0,2.0,0.0,0.0,0.0,-1.0

In [18]:
dispo_alimentaire['test dispo2'] =(dispo_alimentaire['Nourriture']
                                   +dispo_alimentaire['Aliments pour animaux']
                                   +dispo_alimentaire['Pertes']
                                   +dispo_alimentaire['Semences']
                                   +dispo_alimentaire['Traitement']
                                   +dispo_alimentaire['Autres Utilisations']
                                   -dispo_alimentaire['Disponibilité intérieure']
                                  )
dispo_alimentaire[dispo_alimentaire['test dispo2']!=0]

,Zone,Produit,Origine,Aliments pour animaux,Autres Utilisations,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de matière grasse en quantité (g/personne/jour),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock,test dispo1,test dispo2
29,Afghanistan,Lait - Excl Beurre,animale,123.0,0.0,100.0,62.23,5.19,6.12,2083.0,0.0,248.0,1901.0,58.0,1835.0,0.0,0.0,0.0,0.0,-1.0
32,Afghanistan,Maïs,vegetale,200.0,0.0,21.0,2.50,0.30,0.56,313.0,0.0,1.0,76.0,31.0,312.0,5.0,0.0,0.0,0.0,-1.0
38,Afghanistan,Olives,vegetale,0.0,0.0,0.0,0.06,0.03,0.00,7.0,0.0,0.0,2.0,0.0,7.0,0.0,4.0,0.0,0.0,-1.0
40,Afghanistan,Orge,vegetale,360.0,0.0,26.0,2.92,0.24,0.79,524.0,0.0,10.0,89.0,52.0,514.0,22.0,0.0,0.0,0.0,-1.0
41,Afghanistan,"Plantes Oleiferes, Autre",vegetale,0.0,0.0,0.0,0.00,0.00,0.00,3.0,0.0,0.0,0.0,0.0,3.0,0.0,2.0,0.0,0.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15542,Îles Salomon,Coco (Incl Coprah),vegetale,0.0,201.0,217.0,71.30,17.97,2.15,329.0,46.0,0.0,40.0,0.0,384.0,0.0,89.0,-9.0,0.0,1.0
15557,Îles Salomon,Huile de Palmistes,vegetale,0.0,0.0,0.0,0.00,0.00,0.00,-2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
15564,Îles Salomon,Lait - Excl Beurre,animale,0.0,0.0,19.0,11.52,0.70,1.05,7.0,0.0,5.0,6.0,0.0,1.0,0.0,0.0,0.0,-1.0,-1.0
15565,Îles Salomon,"Légumes, Autres",vegetale,0.0,0.0,8.0,12.96,0.06,0.42,8.0,0.0,0.0,7.0,0.0,7.0,0.0,0.0,0.0,-1.0,-1.0
15566,Îles Salomon,Légumineuses Autres,vegetale,0.0,0.0,99.0,10.65,0.59,6.42,7.0,0.0,0.0,6.0,0.0,7.0,0.0,0.0,0.0,0.0,-1.0